### ISSUE TITLE
Script Doesn't Detect all Server 2003/2008 objects

### ISSUE THREAD

**Issue by DrewXT** [takondo/11Bchecker#4]
I've found of recent times that in a larger domain, that the script is only detecting a small subset of legacy operating systems.

Would also be awesome if it can be modded to output to a file

**Comment by takondo** [comment]
You may be seeing limitations on the amount of objects being parsed. You can limit the scope of the search by specifying SearchScope and SearchBase in the search query to specify the OU you want to start the search, and whether the search should be recursive or just in the OU specified.

Example for searching from MyOU recursively.
$computers = Get-ADComputer -filter * -SearchBase "OU=MyOU,DC=contoso,DC=com" -SearchScope 2 -Properties msDS-SupportedEncryptionTypes, operatingSystem, operatingSystemVersion, userAccountControl, passwordLastSet


You can use Start-Transcript and Stop-Transcript to log the outputs to a file. I've added this to the script.

**Comment by An-dir** [comment]
@DrewXT I assume that you thought that "legacy OS" dectection means "old" or "unsupported" OS version. This is not what 11bChecker currently validates. 11BChecker tries to get Windows OperatingSystem with an OperatingSystemVersion **lower that 6.X**

The MS article https://learn.microsoft.com/de-de/windows/win32/sysinfo/operating-system-version the declares that versions below 6 are:
OS Name| Version
-- | --
Windows Server 2003 R2 | 5,2
Windows Server 2003 | 5,2
Windows XP 64-Bit Edition | 5,2
Windows XP | 5,1
Windows 2000 | 5.0

By default the command used in the 11Bchecker script should get all computer objects because in default it is unlimited.

> **-resultsetsize**
> [...] to receive all of the objects, set this parameter to $Null [...]
> **_The default is $Null._**

Source: https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=winserver2012-ps#-resultsetsize 

If you have changed your default for `resultsetsize` you might revert your changes or append "-resultsetsize $null" to the `Get-ADUser` and `Get-ADComputer`commands

You might close the issue on your own if this or something else solved your problem.

**Comment by DrewXT** [comment]
thanks guys - closing out, the updated script sorted it out
